local Players = game:GetService("Players")
local lp = Players.LocalPlayer
local VU = game:GetService('VirtualUser')
local TS = game:GetService('TweenService')
local camera = game:GetService('Workspace').CurrentCamera
local mouse = Players.LocalPlayer:GetMouse()

local repo = 'https://raw.githubusercontent.com/wally-rblx/LinoriaLib/main/'
local Library = loadstring(game:HttpGet(repo .. 'Library.lua'))()
local ThemeManager = loadstring(game:HttpGet(repo .. 'addons/ThemeManager.lua'))()

local w = Library:CreateWindow({
    Title = '['..identifyexecutor()..']'.." Duckyy",
    Center = true,
    AutoShow = true,
})

local main = w:AddTab("main")
local other = w:AddTab("other")

local farm = main:AddLeftGroupbox("Farm")

farm:AddToggle("punch", {
    Text = "Train Strength",
    Default = false,
    ToolTip = "Train ur Strength"
})
Toggles["punch"]:OnChanged(function()
    if lp.Character ~= nil and lp.Character:WaitForChild("Humanoid") then
        for i,v in pairs(lp.Character:GetChildren()) do if v ~= nil and v:IsA("Tool") then lp.Character.Humanoid:UnequipTools(); end end
    end
    wait(.1)
    spawn(function()
        while task.wait(.2) do
            if Toggles["punch"].Value == true then
                -- Script generated by R2Sv2
                -- R2Sv2 developed by Luckyxero

                local A_1 = "Strength"
                local Event = game:GetService("ReplicatedStorage").Events.Train
                Event:FireServer(A_1)
            end
        end
    end)
end)

farm:AddToggle("pushup", {
    Text = "Train Endurance",
    Default = false,
    ToolTip = "Train ur Endurance"
})
Toggles["pushup"]:OnChanged(function()
    if lp.Character ~= nil and lp.Character:WaitForChild("Humanoid") then
        for i,v in pairs(lp.Character:GetChildren()) do if v ~= nil and v:IsA("Tool") then lp.Character.Humanoid:UnequipTools(); end end
    end
    wait(.1)
    spawn(function()
        while task.wait(.2) do
            if Toggles["pushup"].Value == true then
                -- Script generated by R2Sv2
                -- R2Sv2 developed by Luckyxero

                local A_1 = "Endurance"
                local Event = game:GetService("ReplicatedStorage").Events.Train
                Event:FireServer(A_1)
            end
        end
    end)
end)

farm:AddToggle("mana", {
    Text = "Train Psychic",
    Default = false,
    ToolTip = "Train ur Psychic"
})
Toggles["mana"]:OnChanged(function()
    if lp.Character ~= nil and lp.Character:WaitForChild("Humanoid") then
        for i,v in pairs(lp.Character:GetChildren()) do if v ~= nil and v:IsA("Tool") then lp.Character.Humanoid:UnequipTools(); end end
    end
    wait(.1)
    spawn(function()
        while task.wait(.2) do
            if Toggles["mana"].Value == true then
                -- Script generated by R2Sv2
                -- R2Sv2 developed by Luckyxero
                
                local A_1 = "Psychic"
                local Event = game:GetService("ReplicatedStorage").Events.Train
                Event:FireServer(A_1)
            end
        end
    end)
end)

local misc = other:AddLeftGroupbox("misc")
misc:AddButton("Destroy UI", function()
    Library:Unload()
end)

ThemeManager:SetLibrary(Library)
ThemeManager:SetFolder('DuckyyTheme')
ThemeManager:ApplyToTab(other)

local credit = w:AddTab("credit")
local credits = credit:AddLeftGroupbox("list")
credits:AddLabel("Made by Ghost-Ducky#7698")
credits:AddLabel("Library made by Inori")
credits:AddLabel("Save&Load Theme - wally")

if identifyexecutor() then
    print('Hi '..identifyexecutor()..' User!')
end
